// Canadian airports with an IATA code, used by the observer setup guide to help
// an operator pick the region label for their station.
//
// Source: the OurAirports public-domain dataset
// (davidmegginson.github.io/ourairports-data), filtered to iso_country=CA with a
// three-letter IATA code, excluding closed airports. Generated, not hand-typed —
// the codes are the point, so guessing them would defeat the exercise.
//
// `major` marks large/medium airports, which sort first within a province so the
// recognisable ones surface before the bush strips.

export type IataEntry = {
	code: string;
	city: string;
	name: string;
	region: string;
	major?: boolean;
};

export const CA_IATA: IataEntry[] = [
	{ code: 'YBY', city: 'Bonnyville', name: 'Bonnyville Airport', region: 'Alberta', major: true },
	{ code: 'YYC', city: 'Calgary', name: 'Calgary International Airport', region: 'Alberta', major: true },
	{ code: 'YOD', city: 'Cold Lake', name: 'CFB Cold Lake', region: 'Alberta', major: true },
	{ code: 'YEG', city: 'Edmonton', name: 'Edmonton International Airport', region: 'Alberta', major: true },
	{ code: 'YET', city: 'Edson', name: 'Edson Airport', region: 'Alberta', major: true },
	{ code: 'YPY', city: 'Fort Chipewyan', name: 'Fort Chipewyan Airport', region: 'Alberta', major: true },
	{ code: 'YMM', city: 'Fort McMurray', name: 'Fort McMurray International Airport', region: 'Alberta', major: true },
	{ code: 'YQU', city: 'Grande Prairie', name: 'Grande Prairie Airport', region: 'Alberta', major: true },
	{ code: 'YOJ', city: 'High Level', name: 'High Level Airport', region: 'Alberta', major: true },
	{ code: 'YQL', city: 'Lethbridge', name: 'Lethbridge County Airport', region: 'Alberta', major: true },
	{ code: 'YLL', city: 'Lloydminster', name: 'Lloydminster Airport', region: 'Alberta', major: true },
	{ code: 'YXH', city: 'Medicine Hat', name: 'Medicine Hat Regional Airport', region: 'Alberta', major: true },
	{ code: 'YPE', city: 'Peace River', name: 'Peace River Airport', region: 'Alberta', major: true },
	{ code: 'WPC', city: 'Pincher Creek', name: 'Pincher Creek Airport', region: 'Alberta', major: true },
	{ code: 'YOP', city: 'Rainbow Lake', name: 'Rainbow Lake Airport', region: 'Alberta', major: true },
	{ code: 'YZH', city: 'Slave Lake', name: 'Slave Lake Airport', region: 'Alberta', major: true },
	{ code: 'YQF', city: 'Springbrook', name: 'Red Deer Regional Airport', region: 'Alberta', major: true },
	{ code: 'YZU', city: 'Whitecourt', name: 'Whitecourt Airport', region: 'Alberta', major: true },
	{ code: 'JHL', city: 'Albian Village', name: 'Fort MacKay/Albian Aerodrome', region: 'Alberta' },
	{ code: 'YBA', city: 'Banff', name: 'Banff Airport', region: 'Alberta' },
	{ code: 'TIL', city: 'Cheadle', name: 'Cheadle Airport', region: 'Alberta' },
	{ code: 'CFM', city: 'Conklin', name: 'Conklin (Leismer) Airport', region: 'Alberta' },
	{ code: 'YCT', city: 'Coronation', name: 'Coronation Airport', region: 'Alberta' },
	{ code: 'YYM', city: 'Cowley', name: 'Cowley Airport', region: 'Alberta' },
	{ code: 'YOE', city: 'Donnelly', name: 'Donnelly Airport', region: 'Alberta' },
	{ code: 'YDC', city: 'Drayton Valley', name: 'Drayton Valley Industrial Airport', region: 'Alberta' },
	{ code: 'ZFW', city: 'Fairview', name: 'Fairview Airport', region: 'Alberta' },
	{ code: 'HZP', city: 'Fort Mackay', name: 'Fort Mackay / Horizon Airport', region: 'Alberta' },
	{ code: 'NML', city: 'Fort McMurray', name: 'Fort McMurray / Mildred Lake Airport', region: 'Alberta' },
	{ code: 'ZHP', city: 'High Prairie', name: 'High Prairie Airport', region: 'Alberta' },
	{ code: 'YJP', city: 'Hinton', name: 'Jasper-Hinton Airport', region: 'Alberta' },
	{ code: 'YJA', city: 'Jasper', name: 'Jasper Airport', region: 'Alberta' },
	{ code: 'KFM', city: 'Kirby Lake', name: 'Kirby Lake Airport', region: 'Alberta' },
	{ code: 'YLB', city: 'Lac La Biche', name: 'Lac La Biche Airport', region: 'Alberta' },
	{ code: 'PFM', city: 'Primrose', name: 'Primrose Airport', region: 'Alberta' },
	{ code: 'YSD', city: 'Ralston', name: 'Canadian Forces Base Suffield Heliport', region: 'Alberta' },
	{ code: 'YRM', city: 'Rocky Mountain House', name: 'Rocky Mountain House Airport', region: 'Alberta' },
	{ code: 'YFI', city: 'Suncor Energy Site', name: 'Fort Mackay / Firebag', region: 'Alberta' },
	{ code: 'YVG', city: 'Vermilion', name: 'Vermilion Airport', region: 'Alberta' },
	{ code: 'YXX', city: 'Abbotsford', name: 'Abbotsford International Airport', region: 'British Columbia', major: true },
	{ code: 'YAA', city: 'Anahim Lake', name: 'Anahim Lake Airport', region: 'British Columbia', major: true },
	{ code: 'ZEL', city: 'Bella Bella', name: 'Bella Bella (Campbell Island) Airport', region: 'British Columbia', major: true },
	{ code: 'QBC', city: 'Bella Coola', name: 'Bella Coola Airport', region: 'British Columbia', major: true },
	{ code: 'YPZ', city: 'Burns Lake', name: 'Burns Lake Airport', region: 'British Columbia', major: true },
	{ code: 'YZA', city: 'Cache Creek', name: 'Cache Creek-Ashcroft Regional Airport', region: 'British Columbia', major: true },
	{ code: 'YBL', city: 'Campbell River', name: 'Campbell River Airport', region: 'British Columbia', major: true },
	{ code: 'YCG', city: 'Castlegar', name: 'Castlegar/West Kootenay Regional Airport', region: 'British Columbia', major: true },
	{ code: 'YCQ', city: 'Chetwynd', name: 'Chetwynd Airport', region: 'British Columbia', major: true },
	{ code: 'YQQ', city: 'Comox', name: 'Comox Valley International Airport / CFB Comox', region: 'British Columbia', major: true },
	{ code: 'YXC', city: 'Cranbrook', name: 'Cranbrook/Canadian Rockies International Airport', region: 'British Columbia', major: true },
	{ code: 'YDQ', city: 'Dawson Creek', name: 'Dawson Creek Airport', region: 'British Columbia', major: true },
	{ code: 'YDT', city: 'Delta', name: 'Boundary Bay Airport', region: 'British Columbia', major: true },
	{ code: 'YYE', city: 'Fort Nelson', name: 'Fort Nelson Airport', region: 'British Columbia', major: true },
	{ code: 'YXJ', city: 'Fort Saint John', name: 'Fort St John / North Peace Regional Airport', region: 'British Columbia', major: true },
	{ code: 'ZGF', city: 'Grand Forks', name: 'Grand Forks Airport', region: 'British Columbia', major: true },
	{ code: 'YKA', city: 'Kamloops', name: 'Kamloops John Moose Fulton Field Regional Airport', region: 'British Columbia', major: true },
	{ code: 'YLW', city: 'Kelowna', name: 'Kelowna International Airport', region: 'British Columbia', major: true },
	{ code: 'YLY', city: 'Langley', name: 'Langley Airport', region: 'British Columbia', major: true },
	{ code: 'ZMT', city: 'Masset', name: 'Masset Airport', region: 'British Columbia', major: true },
	{ code: 'YCD', city: 'Nanaimo', name: 'Nanaimo Airport', region: 'British Columbia', major: true },
	{ code: 'YYF', city: 'Penticton', name: 'Penticton Airport', region: 'British Columbia', major: true },
	{ code: 'YZT', city: 'Port Hardy', name: 'Port Hardy Airport', region: 'British Columbia', major: true },
	{ code: 'YPW', city: 'Powell River', name: 'Powell River Airport', region: 'British Columbia', major: true },
	{ code: 'YXS', city: 'Prince George', name: 'Prince George (International) Airport', region: 'British Columbia', major: true },
	{ code: 'YPR', city: 'Prince Rupert', name: 'Prince Rupert Airport', region: 'British Columbia', major: true },
	{ code: 'XQU', city: 'Qualicum Beach', name: 'Qualicum Beach Airport', region: 'British Columbia', major: true },
	{ code: 'YQZ', city: 'Quesnel', name: 'Quesnel Airport', region: 'British Columbia', major: true },
	{ code: 'YRV', city: 'Revelstoke', name: 'Revelstoke Airport', region: 'British Columbia', major: true },
	{ code: 'YSN', city: 'Salmon Arm', name: 'Shuswap Regional Airport', region: 'British Columbia', major: true },
	{ code: 'YZP', city: 'Sandspit', name: 'Sandspit Airport', region: 'British Columbia', major: true },
	{ code: 'YYD', city: 'Smithers', name: 'Smithers Airport', region: 'British Columbia', major: true },
	{ code: 'ZST', city: 'Stewart', name: 'Stewart Airport', region: 'British Columbia', major: true },
	{ code: 'YXT', city: 'Terrace', name: 'Northwest Regional Airport Terrace-Kitimat', region: 'British Columbia', major: true },
	{ code: 'YAZ', city: 'Tofino', name: 'Tofino / Long Beach Airport', region: 'British Columbia', major: true },
	{ code: 'YVR', city: 'Vancouver', name: 'Vancouver International Airport', region: 'British Columbia', major: true },
	{ code: 'YVE', city: 'Vernon', name: 'Vernon Regional Airport', region: 'British Columbia', major: true },
	{ code: 'YYJ', city: 'Victoria', name: 'Victoria International Airport', region: 'British Columbia', major: true },
	{ code: 'YWL', city: 'Williams Lake', name: 'Williams Lake Airport', region: 'British Columbia', major: true },
	{ code: 'ZMH', city: '108 Mile', name: 'South Cariboo Region / 108 Mile Airport', region: 'British Columbia' },
	{ code: 'YAL', city: 'Alert Bay', name: 'Alert Bay Airport', region: 'British Columbia' },
	{ code: 'YBF', city: 'Bamfield', name: 'Bamfield Seaplane Base', region: 'British Columbia' },
	{ code: 'YBW', city: 'Bedwell Harbour', name: 'Bedwell Harbour Seaplane Base', region: 'British Columbia' },
	{ code: 'YSX', city: 'Bella Bella', name: 'Bella Bella/Shearwater Seaplane Base', region: 'British Columbia' },
	{ code: 'YRR', city: 'Big Bay', name: 'Stuart Island Airstrip', region: 'British Columbia' },
	{ code: 'XBB', city: 'Blubber Bay', name: 'Blubber Bay Seaplane Base', region: 'British Columbia' },
	{ code: 'YBO', city: 'Bob Quinn Lake', name: 'Bob Quinn Lake Airport', region: 'British Columbia' },
	{ code: 'YGN', city: 'Broughton Island', name: 'Greenway Sound Seaplane Base', region: 'British Columbia' },
	{ code: 'YBH', city: 'Bull Harbour', name: 'Bull Harbour Water Aerodrome', region: 'British Columbia' },
	{ code: 'YHH', city: 'Campbell River', name: 'Campbell River Seaplane Base', region: 'British Columbia' },
	{ code: 'CJH', city: 'Chilko Lake', name: 'Chilko Lake (Tsylos Park Lodge) Airport', region: 'British Columbia' },
	{ code: 'YCW', city: 'Chilliwack', name: 'Chilliwack Airport', region: 'British Columbia' },
	{ code: 'YCF', city: 'Cortes Bay', name: 'Cortes Bay Water Aerodrome', region: 'British Columbia' },
	{ code: 'YCA', city: 'Courtenay', name: 'Courtenay Airpark', region: 'British Columbia' },
	{ code: 'CFQ', city: 'Creston', name: 'Creston Valley Regional Airport - Art Sutcliffe Field', region: 'British Columbia' },
	{ code: 'YDL', city: 'Dease Lake', name: 'Dease Lake Airport', region: 'British Columbia' },
	{ code: 'YRC', city: 'Desolation Sound', name: 'Refuge Cove Seaplane Base', region: 'British Columbia' },
	{ code: 'DGF', city: 'Douglas Lake', name: 'Douglas Lake Airport', region: 'British Columbia' },
	{ code: 'DUQ', city: 'Duncan', name: 'Duncan Airport', region: 'British Columbia' },
	{ code: 'YCZ', city: 'Fairmont Hot Springs', name: 'Fairmont Hot Springs Airport', region: 'British Columbia' },
	{ code: 'SYF', city: 'Gabriola Island', name: 'Silva Bay Seaplane Base', region: 'British Columbia' },
	{ code: 'YMF', city: 'Galiano Island', name: 'Montague Harbour Seaplane Base', region: 'British Columbia' },
	{ code: 'YGE', city: 'Gorge Harbour', name: 'Gorge Harbour Seaplane Base', region: 'British Columbia' },
	{ code: 'YTB', city: 'Hartley Bay', name: 'Hartley Bay Seaplane Base', region: 'British Columbia' },
	{ code: 'YHC', city: 'Hecate Island', name: 'Hakai Passage Water Aerodrome', region: 'British Columbia' },
	{ code: 'YHE', city: 'Hope', name: 'Hope Airport / FVRD Regional Airpark', region: 'British Columbia' },
	{ code: 'YNH', city: 'Hudson\'s Hope', name: 'Hudson\'s Hope Airport', region: 'British Columbia' },
	{ code: 'YRD', city: 'Kimsquit Valley', name: 'Dean River Airport', region: 'British Columbia' },
	{ code: 'YKK', city: 'Kitkatla', name: 'Kitkatla Seaplane Base', region: 'British Columbia' },
	{ code: 'YKT', city: 'Klemtu', name: 'Klemtu Water Aerodrome', region: 'British Columbia' },
	{ code: 'YMU', city: 'Mansons Landing', name: 'Mansons Landing Seaplane Base', region: 'British Columbia' },
	{ code: 'YAQ', city: 'Maple Bay', name: 'Maple Bay Seaplane Base', region: 'British Columbia' },
	{ code: 'YMB', city: 'Merritt', name: 'Merritt Airport', region: 'British Columbia' },
	{ code: 'YAV', city: 'Miners Bay', name: 'Mayne Island Seaplane Base', region: 'British Columbia' },
	{ code: 'ZNU', city: 'Namu', name: 'Namu Water Aerodrome', region: 'British Columbia' },
	{ code: 'ZNA', city: 'Nanaimo', name: 'Nanaimo Harbour Water Aerodrome', region: 'British Columbia' },
	{ code: 'ZOF', city: 'Ocean Falls', name: 'Ocean Falls Seaplane Base', region: 'British Columbia' },
	{ code: 'YPB', city: 'Port Alberni', name: 'Alberni Valley Regional Airport', region: 'British Columbia' },
	{ code: 'YMP', city: 'Port McNeill', name: 'Port McNeill Airport', region: 'British Columbia' },
	{ code: 'WPL', city: 'Powell River', name: 'Powell Lake Seaplane Base', region: 'British Columbia' },
	{ code: 'ZSW', city: 'Prince Rupert', name: 'Prince Rupert/Seal Cove Seaplane Base', region: 'British Columbia' },
	{ code: 'YQJ', city: 'Quadra Island', name: 'April Point Seaplane Base', region: 'British Columbia' },
	{ code: 'ZQS', city: 'Queen Charlotte', name: 'Queen Charlotte City Seaplane Base', region: 'British Columbia' },
	{ code: 'YRN', city: 'Rivers Inlet', name: 'Rivers Inlet Seaplane Base', region: 'British Columbia' },
	{ code: 'YGG', city: 'Salt Spring Island', name: 'Ganges Seaplane Base', region: 'British Columbia' },
	{ code: 'YAJ', city: 'Saturna Island', name: 'Lyall Harbour Seaplane Base', region: 'British Columbia' },
	{ code: 'YHS', city: 'Sechelt', name: 'Sechelt-Gibsons Airport', region: 'British Columbia' },
	{ code: 'YSE', city: 'Squamish', name: 'Squamish Airport', region: 'British Columbia' },
	{ code: 'YIG', city: 'Stuart Island', name: 'Big Bay Seaplane Base', region: 'British Columbia' },
	{ code: 'YTG', city: 'Sullivan Bay', name: 'Sullivan Bay Seaplane Base', region: 'British Columbia' },
	{ code: 'YPT', city: 'Sunshine Coast', name: 'Pender Harbour Seaplane Base', region: 'British Columbia' },
	{ code: 'ZTS', city: 'Tahsis', name: 'Tahsis Seaplane Base', region: 'British Columbia' },
	{ code: 'YGB', city: 'Texada', name: 'Texada Gillies Bay Airport', region: 'British Columbia' },
	{ code: 'YBQ', city: 'Thetis Island', name: 'Telegraph Harbour Seaplane Base', region: 'British Columbia' },
	{ code: 'YTP', city: 'Tofino', name: 'Tofino Harbour Seaplane Base', region: 'British Columbia' },
	{ code: 'YZZ', city: 'Trail', name: 'Trail Regional Airport', region: 'British Columbia' },
	{ code: 'TUX', city: 'Tumbler Ridge', name: 'Tumbler Ridge Airport', region: 'British Columbia' },
	{ code: 'CXH', city: 'Vancouver', name: 'Vancouver Harbour Water Aerodrome', region: 'British Columbia' },
	{ code: 'YWH', city: 'Victoria', name: 'Victoria Harbour Seaplane Base', region: 'British Columbia' },
	{ code: 'CBA', city: 'West Kelowna', name: 'Alpine Heliport', region: 'British Columbia' },
	{ code: 'YWS', city: 'Whistler', name: 'Whistler/Green Lake Water Aerodrome', region: 'British Columbia' },
	{ code: 'YBR', city: 'Brandon', name: 'Brandon Municipal Airport', region: 'Manitoba', major: true },
	{ code: 'YYQ', city: 'Churchill', name: 'Churchill Airport', region: 'Manitoba', major: true },
	{ code: 'YDN', city: 'Dauphin', name: 'Dauphin Barker Airport', region: 'Manitoba', major: true },
	{ code: 'YGM', city: 'Gimli', name: 'Gimli Industrial Park Airport', region: 'Manitoba', major: true },
	{ code: 'YIV', city: 'Island Lake', name: 'Island Lake Airport', region: 'Manitoba', major: true },
	{ code: 'ZJG', city: 'Jenpeg', name: 'Jenpeg Airport', region: 'Manitoba', major: true },
	{ code: 'KES', city: 'Kelsey', name: 'Kelsey Airport', region: 'Manitoba', major: true },
	{ code: 'YLR', city: 'Leaf Rapids', name: 'Leaf Rapids Airport', region: 'Manitoba', major: true },
	{ code: 'YYL', city: 'Lynn Lake', name: 'Lynn Lake Airport', region: 'Manitoba', major: true },
	{ code: 'PIW', city: 'Pikwitonei', name: 'Pikwitonei Airport', region: 'Manitoba', major: true },
	{ code: 'YPG', city: 'Portage la Prairie', name: 'Portage-la-Prairie / Southport Airport', region: 'Manitoba', major: true },
	{ code: 'ZJN', city: 'Swan River', name: 'Swan River Airport', region: 'Manitoba', major: true },
	{ code: 'YQD', city: 'The Pas', name: 'The Pas Airport', region: 'Manitoba', major: true },
	{ code: 'YTD', city: 'Thicket Portage', name: 'Thicket Portage Airport', region: 'Manitoba', major: true },
	{ code: 'YTH', city: 'Thompson', name: 'Thompson Airport', region: 'Manitoba', major: true },
	{ code: 'YWG', city: 'Winnipeg', name: 'Winnipeg / James Armstrong Richardson International Airport', region: 'Manitoba', major: true },
	{ code: 'YBV', city: 'Berens River', name: 'Berens River Airport', region: 'Manitoba' },
	{ code: 'YDV', city: 'Bloodvein River', name: 'Bloodvein River Airport', region: 'Manitoba' },
	{ code: 'YBT', city: 'Brochet', name: 'Brochet Airport', region: 'Manitoba' },
	{ code: 'YCR', city: 'Cross Lake', name: 'Cross Lake (Charlie Sinclair Memorial) Airport', region: 'Manitoba' },
	{ code: 'YFO', city: 'Flin Flon', name: 'Flin Flon Airport', region: 'Manitoba' },
	{ code: 'YGX', city: 'Gillam', name: 'Gillam Airport', region: 'Manitoba' },
	{ code: 'YGO', city: 'Gods Lake Narrows', name: 'Gods Lake Narrows Airport', region: 'Manitoba' },
	{ code: 'ZGI', city: 'Gods River', name: 'Gods River Airport', region: 'Manitoba' },
	{ code: 'ILF', city: 'Ilford', name: 'Ilford Airport', region: 'Manitoba' },
	{ code: 'YKE', city: 'Knee Lake', name: 'Knee Lake Airport', region: 'Manitoba' },
	{ code: 'XLB', city: 'Lac Brochet', name: 'Lac Brochet Airport', region: 'Manitoba' },
	{ code: 'LRQ', city: 'Laurie River', name: 'Laurie River Airport', region: 'Manitoba' },
	{ code: 'ZGR', city: 'Little Grand Rapids', name: 'Little Grand Rapids Airport', region: 'Manitoba' },
	{ code: 'YNE', city: 'Norway House', name: 'Norway House Airport', region: 'Manitoba' },
	{ code: 'YOH', city: 'Oxford House', name: 'Oxford House Airport', region: 'Manitoba' },
	{ code: 'XPP', city: 'Poplar River', name: 'Poplar River Airport', region: 'Manitoba' },
	{ code: 'XPK', city: 'Pukatawagan', name: 'Pukatawagan Airport', region: 'Manitoba' },
	{ code: 'YRS', city: 'Red Sucker Lake', name: 'Red Sucker Lake Airport', region: 'Manitoba' },
	{ code: 'ZTM', city: 'Shamattawa', name: 'Shamattawa Airport', region: 'Manitoba' },
	{ code: 'XSI', city: 'South Indian Lake', name: 'South Indian Lake Airport', region: 'Manitoba' },
	{ code: 'YST', city: 'St. Theresa Point', name: 'St. Theresa Point Airport', region: 'Manitoba' },
	{ code: 'XTL', city: 'Tadoule Lake', name: 'Tadoule Lake Airport', region: 'Manitoba' },
	{ code: 'ZAC', city: 'York Landing', name: 'York Landing Airport', region: 'Manitoba' },
	{ code: 'YCL', city: 'Charlo', name: 'Charlo Airport', region: 'New Brunswick', major: true },
	{ code: 'YFC', city: 'Fredericton', name: 'Fredericton International Airport', region: 'New Brunswick', major: true },
	{ code: 'YCH', city: 'Miramichi', name: 'Miramichi Airport', region: 'New Brunswick', major: true },
	{ code: 'YQM', city: 'Moncton', name: 'Greater Moncton Roméo LeBlanc International Airport', region: 'New Brunswick', major: true },
	{ code: 'YSJ', city: 'Saint John', name: 'Saint John Airport', region: 'New Brunswick', major: true },
	{ code: 'YSL', city: 'Saint-Léonard', name: 'Saint-Léonard Airport', region: 'New Brunswick', major: true },
	{ code: 'ZBF', city: 'South Tetagouche', name: 'Bathurst Airport', region: 'New Brunswick', major: true },
	{ code: 'YDF', city: 'Deer Lake', name: 'Deer Lake Airport', region: 'Newfoundland & Labrador', major: true },
	{ code: 'YQX', city: 'Gander', name: 'Gander International Airport', region: 'Newfoundland & Labrador', major: true },
	{ code: 'YYR', city: 'Goose Bay', name: 'Goose Bay Airport', region: 'Newfoundland & Labrador', major: true },
	{ code: 'YAY', city: 'St. Anthony', name: 'St. Anthony Airport', region: 'Newfoundland & Labrador', major: true },
	{ code: 'YYT', city: 'St. John\'s', name: 'St. John\'s International Airport', region: 'Newfoundland & Labrador', major: true },
	{ code: 'YJT', city: 'Stephenville', name: 'Stephenville Dymond International Airport', region: 'Newfoundland & Labrador', major: true },
	{ code: 'YWK', city: 'Wabush', name: 'Wabush Airport', region: 'Newfoundland & Labrador', major: true },
	{ code: 'YBI', city: 'Black Tickle', name: 'Black Tickle Airport', region: 'Newfoundland & Labrador' },
	{ code: 'YRF', city: 'Cartwright', name: 'Cartwright Airport', region: 'Newfoundland & Labrador' },
	{ code: 'YHG', city: 'Charlottetown', name: 'Charlottetown Airport', region: 'Newfoundland & Labrador' },
	{ code: 'ZUM', city: 'Churchill Falls', name: 'Churchill Falls Airport', region: 'Newfoundland & Labrador' },
	{ code: 'YHO', city: 'Hopedale', name: 'Hopedale Airport', region: 'Newfoundland & Labrador' },
	{ code: 'YMN', city: 'Makkovik', name: 'Makkovik Airport', region: 'Newfoundland & Labrador' },
	{ code: 'YMH', city: 'Mary\'s Harbour', name: 'Mary\'s Harbour Airport', region: 'Newfoundland & Labrador' },
	{ code: 'YDP', city: 'Nain', name: 'Nain Airport', region: 'Newfoundland & Labrador' },
	{ code: 'YNP', city: 'Natuashish', name: 'Natuashish Airport', region: 'Newfoundland & Labrador' },
	{ code: 'YHA', city: 'Port Hope Simpson', name: 'Port Hope Simpson Airport', region: 'Newfoundland & Labrador' },
	{ code: 'YSO', city: 'Postville', name: 'Postville Airport', region: 'Newfoundland & Labrador' },
	{ code: 'YRG', city: 'Rigolet', name: 'Rigolet Airport', region: 'Newfoundland & Labrador' },
	{ code: 'YSV', city: 'Saglek', name: 'Saglek Airport', region: 'Newfoundland & Labrador' },
	{ code: 'YFX', city: 'St. Lewis', name: 'St. Lewis (Fox Harbour) Airport', region: 'Newfoundland & Labrador' },
	{ code: 'YWM', city: 'Williams Harbour', name: 'Williams Harbour Airport', region: 'Newfoundland & Labrador' },
	{ code: 'YOA', city: 'Ekati', name: 'Ekati Airport', region: 'Northwest Territories', major: true },
	{ code: 'YJF', city: 'Fort Liard', name: 'Fort Liard Airport', region: 'Northwest Territories', major: true },
	{ code: 'YFR', city: 'Fort Resolution', name: 'Fort Resolution Airport', region: 'Northwest Territories', major: true },
	{ code: 'YFS', city: 'Fort Simpson', name: 'Fort Simpson Airport', region: 'Northwest Territories', major: true },
	{ code: 'YSM', city: 'Fort Smith', name: 'Fort Smith Airport', region: 'Northwest Territories', major: true },
	{ code: 'YHY', city: 'Hay River', name: 'Hay River / Merlyn Carter Airport', region: 'Northwest Territories', major: true },
	{ code: 'YEV', city: 'Inuvik', name: 'Inuvik Mike Zubko Airport', region: 'Northwest Territories', major: true },
	{ code: 'YVQ', city: 'Norman Wells', name: 'Norman Wells Airport', region: 'Northwest Territories', major: true },
	{ code: 'YWY', city: 'Wrigley', name: 'Wrigley Airport', region: 'Northwest Territories', major: true },
	{ code: 'YZF', city: 'Yellowknife', name: 'Yellowknife International Airport', region: 'Northwest Territories', major: true },
	{ code: 'LAK', city: 'Aklavik', name: 'Aklavik/Freddie Carmichael Airport', region: 'Northwest Territories' },
	{ code: 'YCK', city: 'Colville Lake', name: 'Tommy Kochon Airport', region: 'Northwest Territories' },
	{ code: 'DVK', city: 'Diavik', name: 'Diavik Airport', region: 'Northwest Territories' },
	{ code: 'YWJ', city: 'Déline', name: 'Déline Airport', region: 'Northwest Territories' },
	{ code: 'YGH', city: 'Fort Good Hope', name: 'Fort Good Hope Airport', region: 'Northwest Territories' },
	{ code: 'ZFM', city: 'Fort Mcpherson', name: 'Fort Mcpherson Airport', region: 'Northwest Territories' },
	{ code: 'YFL', city: 'Fort Reliance', name: 'Fort Reliance Seaplane Base', region: 'Northwest Territories' },
	{ code: 'YRA', city: 'Gamètì', name: 'Rae Lakes Airport', region: 'Northwest Territories' },
	{ code: 'DAS', city: 'Great Bear Lake', name: 'Great Bear Lake Airport', region: 'Northwest Territories' },
	{ code: 'YDU', city: 'Kasba Lake', name: 'Kasba Lake Airport', region: 'Northwest Territories' },
	{ code: 'GHK', city: 'Kennedy Lake', name: 'Gahcho Kue', region: 'Northwest Territories' },
	{ code: 'YSG', city: 'Lutselk\'e', name: 'Lutselk\'e Airport', region: 'Northwest Territories' },
	{ code: 'YDW', city: 'Obre Lake', name: 'North of Sixty Airport', region: 'Northwest Territories' },
	{ code: 'YPC', city: 'Paulatuk', name: 'Paulatuk (Nora Aliqatchialuk Ruben) Airport', region: 'Northwest Territories' },
	{ code: 'YSY', city: 'Sachs Harbour', name: 'Sachs Harbour (David Nasogaluak Jr. Saaryuaq) Airport', region: 'Northwest Territories' },
	{ code: 'YNX', city: 'Snap Lake Mine', name: 'Snap Lake Airport', region: 'Northwest Territories' },
	{ code: 'GSL', city: 'Taltheilei Narrows', name: 'Taltheilei Narrows Airport', region: 'Northwest Territories' },
	{ code: 'YUB', city: 'Tuktoyaktuk', name: 'Tuktoyaktuk / James Gruben Airport', region: 'Northwest Territories' },
	{ code: 'ZFN', city: 'Tulita', name: 'Tulita Airport', region: 'Northwest Territories' },
	{ code: 'TNS', city: 'Tungsten', name: 'Tungsten (Cantung) Airport', region: 'Northwest Territories' },
	{ code: 'YHI', city: 'Ulukhaktok', name: 'Ulukhaktok Holman Airport', region: 'Northwest Territories' },
	{ code: 'YFJ', city: 'Wekweètì', name: 'Wekweètì Airport', region: 'Northwest Territories' },
	{ code: 'YLE', city: 'Whatì', name: 'Whatì Airport', region: 'Northwest Territories' },
	{ code: 'YDG', city: 'Digby', name: 'Digby / Annapolis Regional Airport', region: 'Nova Scotia', major: true },
	{ code: 'YZX', city: 'Greenwood', name: 'CFB Greenwood', region: 'Nova Scotia', major: true },
	{ code: 'YHZ', city: 'Halifax', name: 'Halifax / Stanfield International Airport', region: 'Nova Scotia', major: true },
	{ code: 'YPS', city: 'Port Hawkesbury', name: 'Port Hawkesbury Airport', region: 'Nova Scotia', major: true },
	{ code: 'YQY', city: 'Sydney', name: 'Sydney / J.A. Douglas McCurdy Airport', region: 'Nova Scotia', major: true },
	{ code: 'YQI', city: 'Yarmouth', name: 'Yarmouth Airport', region: 'Nova Scotia', major: true },
	{ code: 'YSA', city: 'Sable Island', name: 'Sable Island Airport.', region: 'Nova Scotia' },
	{ code: 'YLT', city: 'Alert', name: 'Alert Airport', region: 'Nunavut', major: true },
	{ code: 'YBK', city: 'Baker Lake', name: 'Baker Lake Airport', region: 'Nunavut', major: true },
	{ code: 'YCB', city: 'Cambridge Bay', name: 'Cambridge Bay Airport', region: 'Nunavut', major: true },
	{ code: 'YZS', city: 'Coral Harbour', name: 'Coral Harbour Airport', region: 'Nunavut', major: true },
	{ code: 'YFB', city: 'Iqaluit', name: 'Iqaluit Airport', region: 'Nunavut', major: true },
	{ code: 'YRT', city: 'Rankin Inlet', name: 'Rankin Inlet Airport', region: 'Nunavut', major: true },
	{ code: 'YRB', city: 'Resolute Bay', name: 'Resolute Bay Airport', region: 'Nunavut', major: true },
	{ code: 'YUX', city: 'Sanirajak', name: 'Hall Beach Airport', region: 'Nunavut', major: true },
	{ code: 'YAB', city: 'Arctic Bay', name: 'Arctic Bay Airport', region: 'Nunavut' },
	{ code: 'YEK', city: 'Arviat', name: 'Arviat Airport', region: 'Nunavut' },
	{ code: 'YCS', city: 'Chesterfield Inlet', name: 'Chesterfield Inlet Airport', region: 'Nunavut' },
	{ code: 'YCY', city: 'Clyde River', name: 'Clyde River Airport', region: 'Nunavut' },
	{ code: 'YEU', city: 'Eureka', name: 'Eureka Airport', region: 'Nunavut' },
	{ code: 'YHK', city: 'Gjoa Haven', name: 'Gjoa Haven Airport', region: 'Nunavut' },
	{ code: 'YGZ', city: 'Grise Fiord', name: 'Grise Fiord Airport', region: 'Nunavut' },
	{ code: 'JOJ', city: 'Hope Bay', name: 'Doris Lake', region: 'Nunavut' },
	{ code: 'UZM', city: 'Hope Bay', name: 'Hope Bay Aerodrome', region: 'Nunavut' },
	{ code: 'YGT', city: 'Igloolik', name: 'Igloolik Airport', region: 'Nunavut' },
	{ code: 'YLC', city: 'Kimmirut', name: 'Kimmirut Airport', region: 'Nunavut' },
	{ code: 'YTE', city: 'Kinngait', name: 'Cape Dorset Airport', region: 'Nunavut' },
	{ code: 'YBB', city: 'Kugaaruk', name: 'Kugaaruk Airport', region: 'Nunavut' },
	{ code: 'YCO', city: 'Kugluktuk', name: 'Kugluktuk Airport', region: 'Nunavut' },
	{ code: 'YMV', city: 'Mary River', name: 'Mary River Aerodrome', region: 'Nunavut' },
	{ code: 'YXP', city: 'Pangnirtung', name: 'Pangnirtung Airport', region: 'Nunavut' },
	{ code: 'YIO', city: 'Pond Inlet', name: 'Pond Inlet Airport', region: 'Nunavut' },
	{ code: 'YVM', city: 'Qikiqtarjuaq', name: 'Qikiqtarjuaq Airport', region: 'Nunavut' },
	{ code: 'YUT', city: 'Repulse Bay', name: 'Naujaat Airport', region: 'Nunavut' },
	{ code: 'YSK', city: 'Sanikiluaq', name: 'Sanikiluaq Airport', region: 'Nunavut' },
	{ code: 'YYH', city: 'Taloyoak', name: 'Taloyoak Airport', region: 'Nunavut' },
	{ code: 'YXN', city: 'Whale Cove', name: 'Whale Cove Airport', region: 'Nunavut' },
	{ code: 'YYW', city: 'Armstrong', name: 'Armstrong Airport', region: 'Ontario', major: true },
	{ code: 'YIB', city: 'Atikokan', name: 'Atikokan Municipal Airport', region: 'Ontario', major: true },
	{ code: 'YLK', city: 'Barrie', name: 'Barrie-Lake Simcoe Regional Airport', region: 'Ontario', major: true },
	{ code: 'YKF', city: 'Breslau', name: 'Region of Waterloo International Airport', region: 'Ontario', major: true },
	{ code: 'YLD', city: 'Chapleau', name: 'Chapleau Airport', region: 'Ontario', major: true },
	{ code: 'YCN', city: 'Cochrane', name: 'Cochrane Airport', region: 'Ontario', major: true },
	{ code: 'YCC', city: 'Cornwall', name: 'Cornwall Regional Airport', region: 'Ontario', major: true },
	{ code: 'YHD', city: 'Dryden', name: 'Dryden Regional Airport', region: 'Ontario', major: true },
	{ code: 'YXR', city: 'Earlton', name: 'Earlton (Timiskaming Regional) Airport', region: 'Ontario', major: true },
	{ code: 'YEL', city: 'Elliot Lake', name: 'Elliot Lake Municipal Airport', region: 'Ontario', major: true },
	{ code: 'YAG', city: 'Fort Frances', name: 'Fort Frances Municipal Airport', region: 'Ontario', major: true },
	{ code: 'YGQ', city: 'Geraldton', name: 'Geraldton Greenstone Regional Airport', region: 'Ontario', major: true },
	{ code: 'YZE', city: 'Gore Bay', name: 'Gore Bay Manitoulin Airport', region: 'Ontario', major: true },
	{ code: 'YQA', city: 'Gravenhurst', name: 'Muskoka Airport', region: 'Ontario', major: true },
	{ code: 'YHM', city: 'Hamilton', name: 'John C. Munro Hamilton International Airport', region: 'Ontario', major: true },
	{ code: 'YHF', city: 'Hearst', name: 'Hearst René Fontaine Municipal Airport', region: 'Ontario', major: true },
	{ code: 'YHN', city: 'Hornepayne', name: 'Hornepayne Municipal Airport', region: 'Ontario', major: true },
	{ code: 'YCE', city: 'Huron Park', name: 'Centralia / James T. Field Memorial Aerodrome', region: 'Ontario', major: true },
	{ code: 'ZUC', city: 'Ignace', name: 'Ignace Municipal Airport', region: 'Ontario', major: true },
	{ code: 'YYU', city: 'Kapuskasing', name: 'Kapuskasing Airport', region: 'Ontario', major: true },
	{ code: 'XKS', city: 'Kasabonika', name: 'Kasabonika Airport', region: 'Ontario', major: true },
	{ code: 'YQK', city: 'Kenora', name: 'Kenora Airport', region: 'Ontario', major: true },
	{ code: 'YKD', city: 'Kincardine', name: 'Kincardine Municipal Airport', region: 'Ontario', major: true },
	{ code: 'YGK', city: 'Kingston', name: 'Kingston Norman Rogers Airport', region: 'Ontario', major: true },
	{ code: 'YKX', city: 'Kirkland Lake', name: 'Kirkland Lake Airport', region: 'Ontario', major: true },
	{ code: 'YXU', city: 'London', name: 'London International Airport', region: 'Ontario', major: true },
	{ code: 'YMG', city: 'Manitouwadge', name: 'Manitouwadge Airport', region: 'Ontario', major: true },
	{ code: 'YSP', city: 'Marathon', name: 'Marathon Airport', region: 'Ontario', major: true },
	{ code: 'YMO', city: 'Moosonee', name: 'Moosonee Airport', region: 'Ontario', major: true },
	{ code: 'YQN', city: 'Nakina', name: 'Nakina Airport', region: 'Ontario', major: true },
	{ code: 'YCM', city: 'Niagara-on-the-Lake', name: 'Niagara District Airport', region: 'Ontario', major: true },
	{ code: 'YYB', city: 'North Bay', name: 'North Bay Jack Garland Airport', region: 'Ontario', major: true },
	{ code: 'YOO', city: 'Oshawa', name: 'Oshawa Executive Airport', region: 'Ontario', major: true },
	{ code: 'YOW', city: 'Ottawa', name: 'Ottawa Macdonald-Cartier International Airport', region: 'Ontario', major: true },
	{ code: 'YRO', city: 'Ottawa', name: 'Ottawa / Rockcliffe Airport', region: 'Ontario', major: true },
	{ code: 'YOS', city: 'Owen Sound', name: 'Owen Sound / Billy Bishop Regional Airport', region: 'Ontario', major: true },
	{ code: 'YTA', city: 'Pembroke', name: 'Pembroke Airport', region: 'Ontario', major: true },
	{ code: 'YPQ', city: 'Peterborough', name: 'Peterborough Regional Airport', region: 'Ontario', major: true },
	{ code: 'YPL', city: 'Pickle Lake', name: 'Pickle Lake Airport', region: 'Ontario', major: true },
	{ code: 'YRL', city: 'Red Lake', name: 'Red Lake Airport', region: 'Ontario', major: true },
	{ code: 'ZSJ', city: 'Sandy Lake', name: 'Sandy Lake Airport', region: 'Ontario', major: true },
	{ code: 'YZR', city: 'Sarnia', name: 'Chris Hadfield Airport', region: 'Ontario', major: true },
	{ code: 'YAM', city: 'Sault Ste Marie', name: 'Sault Ste Marie Airport', region: 'Ontario', major: true },
	{ code: 'YEM', city: 'Sheguiandah', name: 'Manitoulin East Municipal Airport', region: 'Ontario', major: true },
	{ code: 'YXL', city: 'Sioux Lookout', name: 'Sioux Lookout Airport', region: 'Ontario', major: true },
	{ code: 'YSH', city: 'Smiths Falls', name: 'Smiths Falls-Montague (Russ Beach) Airport', region: 'Ontario', major: true },
	{ code: 'YQS', city: 'St Thomas', name: 'St Thomas Municipal Airport', region: 'Ontario', major: true },
	{ code: 'YSB', city: 'Sudbury', name: 'Sudbury Airport', region: 'Ontario', major: true },
	{ code: 'YQT', city: 'Thunder Bay', name: 'Thunder Bay International Airport', region: 'Ontario', major: true },
	{ code: 'YTS', city: 'Timmins', name: 'Timmins/Victor M. Power', region: 'Ontario', major: true },
	{ code: 'YTZ', city: 'Toronto', name: 'Billy Bishop Toronto City Airport', region: 'Ontario', major: true },
	{ code: 'YYZ', city: 'Toronto', name: 'Toronto Pearson International Airport', region: 'Ontario', major: true },
	{ code: 'YTR', city: 'Trenton', name: 'CFB Trenton', region: 'Ontario', major: true },
	{ code: 'YXZ', city: 'Wawa', name: 'Wawa Airport', region: 'Ontario', major: true },
	{ code: 'YVV', city: 'Wiarton', name: 'Wiarton Airport', region: 'Ontario', major: true },
	{ code: 'YQG', city: 'Windsor', name: 'Windsor International Airport', region: 'Ontario', major: true },
	{ code: 'YAX', city: 'Angling Lake', name: 'Wapekeka Airport', region: 'Ontario' },
	{ code: 'YAT', city: 'Attawapiskat', name: 'Attawapiskat Airport', region: 'Ontario' },
	{ code: 'XBE', city: 'Bearskin Lake', name: 'Bearskin Lake Airport', region: 'Ontario' },
	{ code: 'YTL', city: 'Big Trout Lake', name: 'Big Trout Lake Airport', region: 'Ontario' },
	{ code: 'XBR', city: 'Brockville', name: 'Brockville - Thousand Islands Regional Tackaberry Airport', region: 'Ontario' },
	{ code: 'YAC', city: 'Cat Lake', name: 'Cat Lake Airport', region: 'Ontario' },
	{ code: 'XCM', city: 'Chatham-Kent', name: 'Chatham Kent Airport', region: 'Ontario' },
	{ code: 'YVZ', city: 'Deer Lake', name: 'Deer Lake Airport', region: 'Ontario' },
	{ code: 'YEB', city: 'Echo Bay', name: 'Bar River Airport', region: 'Ontario' },
	{ code: 'YFA', city: 'Fort Albany', name: 'Fort Albany Airport', region: 'Ontario' },
	{ code: 'YFH', city: 'Fort Hope', name: 'Fort Hope Airport', region: 'Ontario' },
	{ code: 'YER', city: 'Fort Severn', name: 'Fort Severn Airport', region: 'Ontario' },
	{ code: 'YSI', city: 'Frying Pan Island', name: 'Parry Sound/Frying Pan Island-Sans Souci Seaplane Base', region: 'Ontario' },
	{ code: 'ZKE', city: 'Kashechewan', name: 'Kashechewan Airport', region: 'Ontario' },
	{ code: 'KEW', city: 'Keewaywin', name: 'Keewaywin Airport', region: 'Ontario' },
	{ code: 'KIF', city: 'Kingfisher Lake', name: 'Kingfisher Lake Airport', region: 'Ontario' },
	{ code: 'YLH', city: 'Lansdowne House', name: 'Lansdowne House Airport', region: 'Ontario' },
	{ code: 'MSA', city: 'Muskrat Dam', name: 'Muskrat Dam Airport', region: 'Ontario' },
	{ code: 'YNO', city: 'North Spirit Lake', name: 'North Spirit Lake Airport', region: 'Ontario' },
	{ code: 'YOG', city: 'Ogoki Post', name: 'Ogoki Post Airport', region: 'Ontario' },
	{ code: 'YBS', city: 'Opapimiskan Lake', name: 'Opapimiskan Lake Airport', region: 'Ontario' },
	{ code: 'YPD', city: 'Parry Sound', name: 'Parry Sound Area Municipal Airport', region: 'Ontario' },
	{ code: 'YPO', city: 'Peawanuck', name: 'Peawanuck Airport', region: 'Ontario' },
	{ code: 'YWA', city: 'Petawawa', name: 'Petawawa Heliport', region: 'Ontario' },
	{ code: 'YPM', city: 'Pikangikum', name: 'Pikangikum Airport', region: 'Ontario' },
	{ code: 'YHP', city: 'Poplar Hill', name: 'Poplar Hill Airport', region: 'Ontario' },
	{ code: 'ZRJ', city: 'Round Lake', name: 'Round Lake (Weagamow Lake) Airport', region: 'Ontario' },
	{ code: 'ZPB', city: 'Sachigo Lake', name: 'Sachigo Lake Airport', region: 'Ontario' },
	{ code: 'SUR', city: 'Summer Beaver', name: 'Summer Beaver Airport', region: 'Ontario' },
	{ code: 'YWP', city: 'Webequie', name: 'Webequie Airport', region: 'Ontario' },
	{ code: 'YWR', city: 'White River', name: 'White River Seaplane Base', region: 'Ontario' },
	{ code: 'WNN', city: 'Wunnumin Lake', name: 'Wunnumin Lake Airport', region: 'Ontario' },
	{ code: 'YYG', city: 'Charlottetown', name: 'Charlottetown Airport', region: 'Prince Edward Island', major: true },
	{ code: 'YSU', city: 'Slemon Park', name: 'Summerside Airport', region: 'Prince Edward Island', major: true },
	{ code: 'YTF', city: 'Alma', name: 'Alma Airport', region: 'Quebec', major: true },
	{ code: 'YEY', city: 'Amos', name: 'Amos/Magny Airport', region: 'Quebec', major: true },
	{ code: 'YBC', city: 'Baie-Comeau', name: 'Baie-Comeau Airport', region: 'Quebec', major: true },
	{ code: 'YBX', city: 'Blanc-Sablon', name: 'Lourdes-de-Blanc-Sablon Airport', region: 'Quebec', major: true },
	{ code: 'YVB', city: 'Bonaventure', name: 'Bonaventure Airport', region: 'Quebec', major: true },
	{ code: 'ZBM', city: 'Bromont', name: 'Bromont (Roland Désourdy) Airport', region: 'Quebec', major: true },
	{ code: 'YML', city: 'Charlevoix', name: 'Charlevoix Airport', region: 'Quebec', major: true },
	{ code: 'YMT', city: 'Chibougamau', name: 'Chapais Airport', region: 'Quebec', major: true },
	{ code: 'YDO', city: 'Dolbeau-Saint-Felicien', name: 'Dolbeau-Saint-Felicien Airport', region: 'Quebec', major: true },
	{ code: 'YFE', city: 'Forestville', name: 'Forestville Airport', region: 'Quebec', major: true },
	{ code: 'YGP', city: 'Gaspé', name: 'Michel-Pouliot Gaspé Airport', region: 'Quebec', major: true },
	{ code: 'YND', city: 'Gatineau', name: 'Ottawa / Gatineau Airport', region: 'Quebec', major: true },
	{ code: 'YGV', city: 'Havre-Saint-Pierre', name: 'Havre-Saint-Pierre Airport', region: 'Quebec', major: true },
	{ code: 'YVP', city: 'Kuujjuaq', name: 'Kuujjuaq Airport', region: 'Quebec', major: true },
	{ code: 'YGW', city: 'Kuujjuarapik', name: 'Kuujjuarapik Airport', region: 'Quebec', major: true },
	{ code: 'YGL', city: 'La Grande Rivière', name: 'La Grande Rivière Airport', region: 'Quebec', major: true },
	{ code: 'YAH', city: 'La Grande-4', name: 'La Grande-4 Airport', region: 'Quebec', major: true },
	{ code: 'YTM', city: 'La Macaza', name: 'Mont-Tremblant International Airport', region: 'Quebec', major: true },
	{ code: 'YGR', city: 'Les Îles-de-la-Madeleine', name: 'Îles-de-la-Madeleine Airport', region: 'Quebec', major: true },
	{ code: 'YNM', city: 'Matagami', name: 'Matagami Airport', region: 'Quebec', major: true },
	{ code: 'YME', city: 'Matane', name: 'Matane Airport', region: 'Quebec', major: true },
	{ code: 'YYY', city: 'Mont-Joli', name: 'Mont Joli Airport', region: 'Quebec', major: true },
	{ code: 'YHU', city: 'Montréal', name: 'Montréal / Saint-Hubert Metropolitan Airport', region: 'Quebec', major: true },
	{ code: 'YMX', city: 'Montréal', name: 'Montreal Mirabel International Airport', region: 'Quebec', major: true },
	{ code: 'YUL', city: 'Montréal', name: 'Montreal / Pierre Elliott Trudeau International Airport', region: 'Quebec', major: true },
	{ code: 'YNA', city: 'Natashquan', name: 'Natashquan Airport', region: 'Quebec', major: true },
	{ code: 'YPN', city: 'Port-Menier', name: 'Port-Menier Airport', region: 'Quebec', major: true },
	{ code: 'YPX', city: 'Puvirnituq', name: 'Puvirnituq Airport', region: 'Quebec', major: true },
	{ code: 'YQB', city: 'Quebec', name: 'Quebec Jean Lesage International Airport', region: 'Quebec', major: true },
	{ code: 'YXK', city: 'Rimouski', name: 'Rimouski Airport', region: 'Quebec', major: true },
	{ code: 'YRI', city: 'Rivière-du-Loup', name: 'Rivière-du-Loup Airport', region: 'Quebec', major: true },
	{ code: 'YRJ', city: 'Roberval', name: 'Roberval Airport', region: 'Quebec', major: true },
	{ code: 'YUY', city: 'Rouyn-Noranda', name: 'Rouyn Noranda Airport', region: 'Quebec', major: true },
	{ code: 'YBG', city: 'Saguenay', name: 'Saguenay-Bagotville Airport', region: 'Quebec', major: true },
	{ code: 'YKL', city: 'Schefferville', name: 'Schefferville Airport', region: 'Quebec', major: true },
	{ code: 'YZV', city: 'Sept-Îles', name: 'Sept-Îles Airport', region: 'Quebec', major: true },
	{ code: 'YSC', city: 'Sherbrooke', name: 'Sherbrooke Airport', region: 'Quebec', major: true },
	{ code: 'YJN', city: 'St Jean', name: 'St Jean Airport', region: 'Quebec', major: true },
	{ code: 'YIF', city: 'St-Augustin', name: 'St Augustin Airport', region: 'Quebec', major: true },
	{ code: 'YRQ', city: 'Trois-Rivières', name: 'Trois-Rivières Airport', region: 'Quebec', major: true },
	{ code: 'YVO', city: 'Val-d\'Or', name: 'Val-d\'Or Airport', region: 'Quebec', major: true },
	{ code: 'AKV', city: 'Akulivik', name: 'Akulivik Airport', region: 'Quebec' },
	{ code: 'YPJ', city: 'Aupaluk', name: 'Aupaluk Airport', region: 'Quebec' },
	{ code: 'YBJ', city: 'Baie-Johan-Beetz', name: 'Baie-Johan-Beetz Water Aerodrome', region: 'Quebec' },
	{ code: 'YHR', city: 'Chevery', name: 'Chevery Airport', region: 'Quebec' },
	{ code: 'YKU', city: 'Chisasibi', name: 'Chisasibi Airport', region: 'Quebec' },
	{ code: 'YWQ', city: 'Chutes-des-Passes', name: 'Chute-Des-Passes/Lac Margane Seaplane Base', region: 'Quebec' },
	{ code: 'ZKG', city: 'Côte-Nord-du-Golfe-du-Saint-Laurent', name: 'Kégashka Airport', region: 'Quebec' },
	{ code: 'ZEM', city: 'Eastmain River', name: 'Eastmain River Airport', region: 'Quebec' },
	{ code: 'YFG', city: 'Fontanges', name: 'Fontanges Airport', region: 'Quebec' },
	{ code: 'YPH', city: 'Inukjuak', name: 'Inukjuak Airport', region: 'Quebec' },
	{ code: 'YIK', city: 'Ivujivik', name: 'Ivujivik Airport', region: 'Quebec' },
	{ code: 'XGR', city: 'Kangiqsualujjuaq', name: 'Kangiqsualujjuaq (Georges River) Airport', region: 'Quebec' },
	{ code: 'YWB', city: 'Kangiqsujuaq', name: 'Kangiqsujuaq (Wakeham Bay) Airport', region: 'Quebec' },
	{ code: 'YKG', city: 'Kangirsuk', name: 'Kangirsuk Airport', region: 'Quebec' },
	{ code: 'YAU', city: 'Kattiniq', name: 'Donaldson Airport', region: 'Quebec' },
	{ code: 'YAR', city: 'La Grande-3', name: 'La Grande-3 Airport', region: 'Quebec' },
	{ code: 'SSQ', city: 'La Sarre', name: 'La Sarre Airport', region: 'Quebec' },
	{ code: 'ZLT', city: 'La Tabatière', name: 'La Tabatière Airport', region: 'Quebec' },
	{ code: 'YLQ', city: 'La Tuque', name: 'La Tuque Airport', region: 'Quebec' },
	{ code: 'ZGS', city: 'Le Golfe-du-Saint-Laurent', name: 'La Romaine Airport', region: 'Quebec' },
	{ code: 'YLS', city: 'Lebel-sur-Quévillon', name: 'Lebel-sur-Quevillon Airport', region: 'Quebec' },
	{ code: 'YLP', city: 'Longue-Pointe-de-Mingan', name: 'Mingan Airport', region: 'Quebec' },
	{ code: 'YMW', city: 'Messines', name: 'Maniwaki Airport', region: 'Quebec' },
	{ code: 'YNS', city: 'Nemiscau', name: 'Nemiscau Airport', region: 'Quebec' },
	{ code: 'YQC', city: 'Quaqtaq', name: 'Quaqtaq Airport', region: 'Quebec' },
	{ code: 'YZG', city: 'Salluit', name: 'Salluit Airport', region: 'Quebec' },
	{ code: 'YTQ', city: 'Tasiujaq', name: 'Tasiujaq Airport', region: 'Quebec' },
	{ code: 'ZTB', city: 'Tête-à-la-Baleine', name: 'Tête-à-la-Baleine Airport', region: 'Quebec' },
	{ code: 'YUD', city: 'Umiujaq', name: 'Umiujaq Airport', region: 'Quebec' },
	{ code: 'YKQ', city: 'Waskaganish', name: 'Waskaganish Airport', region: 'Quebec' },
	{ code: 'YNC', city: 'Wemindji', name: 'Wemindji Airport', region: 'Quebec' },
	{ code: 'YOI', city: 'Éléonore Mine', name: 'Opinaca Aerodrome', region: 'Quebec' },
	{ code: 'YEN', city: 'Estevan', name: 'Estevan Airport', region: 'Saskatchewan', major: true },
	{ code: 'YKJ', city: 'Key Lake', name: 'Key Lake Airport', region: 'Saskatchewan', major: true },
	{ code: 'YKY', city: 'Kindersley', name: 'Kindersley Airport', region: 'Saskatchewan', major: true },
	{ code: 'YVC', city: 'La Ronge', name: 'La Ronge Airport', region: 'Saskatchewan', major: true },
	{ code: 'YLJ', city: 'Meadow Lake', name: 'Meadow Lake Airport', region: 'Saskatchewan', major: true },
	{ code: 'YMJ', city: 'Moose Jaw', name: 'Moose Jaw Air Vice Marshal C. M. McEwen Airport', region: 'Saskatchewan', major: true },
	{ code: 'YQW', city: 'North Battleford', name: 'North Battleford Airport', region: 'Saskatchewan', major: true },
	{ code: 'YNL', city: 'Points North Landing', name: 'Points North Landing Airport', region: 'Saskatchewan', major: true },
	{ code: 'YPA', city: 'Prince Albert', name: 'Prince Albert Glass Field', region: 'Saskatchewan', major: true },
	{ code: 'YQR', city: 'Regina', name: 'Regina International Airport', region: 'Saskatchewan', major: true },
	{ code: 'YXE', city: 'Saskatoon', name: 'Saskatoon John G. Diefenbaker International Airport', region: 'Saskatchewan', major: true },
	{ code: 'YSF', city: 'Stony Rapids', name: 'Stony Rapids Airport', region: 'Saskatchewan', major: true },
	{ code: 'YYN', city: 'Swift Current', name: 'Swift Current Airport', region: 'Saskatchewan', major: true },
	{ code: 'YQV', city: 'Yorkton', name: 'Yorkton Municipal Airport', region: 'Saskatchewan', major: true },
	{ code: 'YVT', city: 'Buffalo Narrows', name: 'Buffalo Narrows Airport', region: 'Saskatchewan' },
	{ code: 'XCL', city: 'Cluff Lake', name: 'Cluff Lake Airport', region: 'Saskatchewan' },
	{ code: 'YKC', city: 'Collins Bay', name: 'Collins Bay Airport', region: 'Saskatchewan' },
	{ code: 'ZFD', city: 'Fond-du-Lac', name: 'Fond-du-Lac Airport', region: 'Saskatchewan' },
	{ code: 'YDJ', city: 'Hatchet Lake', name: 'Hatchet Lake Airport', region: 'Saskatchewan' },
	{ code: 'YHB', city: 'Hudson Bay', name: 'Hudson Bay Airport', region: 'Saskatchewan' },
	{ code: 'ZPO', city: 'Pinehouse Lake', name: 'Pinehouse Lake Airport', region: 'Saskatchewan' },
	{ code: 'YTT', city: 'Tisdale', name: 'Tisdale Airport', region: 'Saskatchewan' },
	{ code: 'YBE', city: 'Uranium City', name: 'Uranium City Airport', region: 'Saskatchewan' },
	{ code: 'ZWL', city: 'Wollaston Lake', name: 'Wollaston Lake Airport', region: 'Saskatchewan' },
	{ code: 'YXQ', city: 'Beaver Creek', name: 'Beaver Creek Airport', region: 'Yukon', major: true },
	{ code: 'YDB', city: 'Burwash Landing', name: 'Burwash Airport', region: 'Yukon', major: true },
	{ code: 'YDA', city: 'Dawson City', name: 'Dawson City Airport', region: 'Yukon', major: true },
	{ code: 'ZFA', city: 'Faro', name: 'Faro Airport', region: 'Yukon', major: true },
	{ code: 'YHT', city: 'Haines Junction', name: 'Haines Junction Airport', region: 'Yukon', major: true },
	{ code: 'YMA', city: 'Mayo', name: 'Mayo Airport', region: 'Yukon', major: true },
	{ code: 'XRR', city: 'Ross River', name: 'Ross River Airport', region: 'Yukon', major: true },
	{ code: 'YZW', city: 'Teslin', name: 'Teslin Airport', region: 'Yukon', major: true },
	{ code: 'YQH', city: 'Watson Lake', name: 'Watson Lake Airport', region: 'Yukon', major: true },
	{ code: 'YXY', city: 'Whitehorse', name: 'Whitehorse / Erik Nielsen International Airport', region: 'Yukon', major: true },
	{ code: 'XMP', city: 'Macmillan Pass', name: 'Macmillan Pass Airport', region: 'Yukon' },
	{ code: 'YOC', city: 'Old Crow', name: 'Old Crow Airport', region: 'Yukon' },
];
